#  Public Server docker services
#
#  Author: Tim Molteno tim@molteno.net.
#  Copyright (C) 2021
#


version: '3.4'
services:


    openvpn:
        cap_add:
            - NET_ADMIN
        image: kylemanna/openvpn
        container_name: openvpn_server
        devices:
            - /dev/net/tun
        # we have to add the webserver ports here as the external_website is using the network stack of openvpn
        ports:
            - "1194:1194/udp"
            - 8088:80         # Notice that this port is the nginx webserver port!
                              # It goes here because the nginx is using the "service:openvpn" network.
        restart: unless-stopped
        volumes:
            - ./openvpn-data/conf:/etc/openvpn
        logging:
            driver: "json-file"
            options:
                max-file: "5"
                max-size: "1m"
        # Clients are allocated static IPs during the setup as static IP addresses
        extra_hosts:
            - client.a:10.0.0.33
            - client.b:10.0.0.22
      
    reverse:
        image: nginx:latest
        network_mode: "service:openvpn"
        volumes:
            - ./nginx_server.conf:/etc/nginx/conf.d/default.conf
            - ./server_content:/var/www/html
            - nginx_cache:/data/nginx
        restart: always
        logging:
            driver: "json-file"
            options:
                max-file: "5"
                max-size: "1m"
        
volumes:
    nginx_cache:
