#  Client (worker) docker services
#
#  Author: Tim Molteno tim@molteno.net.
#  Copyright (C) 2021
#

version: '3.4'

services:
    client_vpn:
        image: dperson/openvpn-client
            # cap_add, security_opt, and volume required for the image to function
        cap_add:
            - net_admin
        environment:
            TZ: 'EST5EDT'
        networks:
            - default
        read_only: true
        tmpfs:
            - /run
            - /tmp
        restart: unless-stopped
        security_opt:
            - label:disable
        stdin_open: true
        tty: true
        volumes:
            - /dev/net:/dev/net:z
            - ./vpn:/vpn
        logging:
            driver: "json-file"
            options:
                max-file: "5"
                max-size: "1m"

    home_server:
        image: nginx:latest
        container_name: client_nginx
        network_mode: "service:client_vpn"
        volumes:
            - ./nginx_client.conf:/etc/nginx/conf.d/default.conf
            - ./client_content:/var/www/html
        restart: always
        logging:
            driver: "json-file"
            options:
                max-file: "5"
                max-size: "1m"

